services:
    sonata.admin.post:
        class: AdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]

    sonata.admin.category:
        class: AdminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - AppBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AdminBundle]]