services:
    api.post_manager:
        class: Application\Backend\ApiBundle\Service\PostManager
        arguments: [@doctrine.orm.entity_manager]

    api.category_manager:
        class: Application\Backend\ApiBundle\Service\CategoryManager
        arguments: [@doctrine.orm.entity_manager]